framy:
  ssh_options:
    user: pi
  properties:
    nopasswd_sudo: true
    run_list:
      - recipes/default.rb
spotty:
  ssh_options:
    user: pi
  properties:
    nopasswd_sudo: true
    run_list:
      - recipes/default.rb
painty:
  ssh_options:
    user: pi
  properties:
    nopasswd_sudo: true
    run_list:
      - recipes/default.rb
